### ISSUE TITLE
Navigate without needing to use enter

### ISSUE THREAD

**Issue by ruudk** [matthiasnoback/php-ast-inspector#5]
It would be great to type `d`, `d`, `d` to quickly navigate instead of `d + enter`, `d + enter`.

**Comment by ruudk** [comment]
Or even better, use the arrow keys to go up and down, and right (inspect) or left (back to parent).

**Comment by matthiasnoback** [comment]
Good idea, I think this will make the experience more "smooth". For me it makes sense to support both ways (asdw and left/right/etc.). I already looked into `QuestionHelper` because I actually wanted it to work like this from the start, to get the full "game experience", but couldn't figure it out quickly. If you have any suggestions, or want to make the change, let me know!
